### ISSUE TITLE
Failed run?

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/tournament#19]
I ran the tournament and got:

```
tournament(gh-pages): ./update_results.sh 0 100
-- Regenerating noisy tournament figures
Starting basic_strategies tournament with 100 round robins of 200 turns per pair.
Finished all basic_strategies tasks in 9.0s
Starting strategies tournament with 100 round robins of 200 turns per pair.
Finished all strategies tasks in 4050.2s
Starting all_strategies tournament with 100 round robins of 200 turns per pair.
Finished all all_strategies tasks in 3483.8s
Finished all tournaments in 7543.0s
-- Running Axelrod, regenerating cache, results, and figures
Starting basic_strategies tournament with 100 round robins of 200 turns per pair.
Finished all basic_strategies tasks in 7.9s
Starting strategies tournament with 100 round robins of 200 turns per pair.
Finished all strategies tasks in 2765.7s
Starting all_strategies tournament with 100 round robins of 200 turns per pair.
Traceback (most recent call last):
  File "./run_axelrod", line 116, in <module>
    run_tournaments(**kwargs)
  File "/home/vince/Axelrod/axelrod/utils.py", line 71, in run_tournaments
    manager.run_tournaments()
  File "/home/vince/Axelrod/axelrod/tournament_manager.py", line 53, in run_tournaments
    self._run_single_tournament(tournament)
  File "/home/vince/Axelrod/axelrod/tournament_manager.py", line 84, in _run_single_tournament
    self._generate_output_files(tournament, ecosystem)
  File "/home/vince/Axelrod/axelrod/tournament_manager.py", line 115, in _generate_output_files
    image_format=self._image_format)
  File "/home/vince/Axelrod/axelrod/tournament_manager.py", line 135, in _save_plots
    self._save_plot(figure, file_name)
  File "/home/vince/Axelrod/axelrod/tournament_manager.py", line 149, in _save_plot
    figure.savefig(file_name, bbox_inches='tight', dpi=dpi)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/figure.py", line 1539, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.py", line 197, in print_figure
    self.draw()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.py", line 158, in draw
    FigureCanvasAgg.draw(self)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py", line 474, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/figure.py", line 1133, in draw
    func(*args)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 2304, in draw
    a.draw(renderer)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/collections.py", line 815, in draw
    Collection.draw(self, renderer)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/collections.py", line 316, in draw
    mpath.Path(offsets), transOffset, tuple(facecolors[0]))
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py", line 123, in draw_markers
    return self._renderer.draw_markers(*kl, **kw)
OverflowError: In draw_markers: Exceeded cell block limit
```

Not sure if this is reproducible yet (could just have bugged out...). This is all viewable on the `failedrun` branch.

**Comment by langner** [comment]
I had a clean run with fewer turns and repetitions (did not want to wait a few hours). This would be much easier to debug if there was an option to skip the tournament and only generate plots.

**Comment by drvinceknight** [comment]
> I had a clean run with fewer turns and repetitions (did not want to wait a few hours). This would be much easier to debug if there was an option to skip the tournament and only generate plots.

@marcharper had a "full" clean run when using py3, what were you using?

**Comment by langner** [comment]
2.7

**Comment by drvinceknight** [comment]
@marcharper said:

> looks like the multiprocessing pipes full issue?

I can't say I have much of a clue...

As far as that option to skip the tournament you mentioned, are you talking about plotting an empty tournament?

**Comment by langner** [comment]
No, I meant generating plots using outputs (CSV files) from a previous run.

**Comment by drvinceknight** [comment]
Ah I understand. :+1: Not sure if that should be in the update results script but sure should be able to create a `Results` instance from data... Not sure if that's implemented or not...
