### ISSUE TITLE
Getting a bug when running `update_results` (something to do with pickling and backstabber)

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/tournament#31]
This is when running from the `509` branch on the main repo (to be able to generate the new figures):

Running with:

```
./update_results.sh 0 1
```

```
Axelrod-tournament(gh-pages) ✗: ./update_results.sh 0 1
-- Regenerating noisy tournament figures
Starting basic_strategies tournament: Turns: 200, Repetitions: 1, Strategies: 8.
Finished all basic_strategies tasks in 13.4s
Starting ordinary_strategies tournament: Turns: 200, Repetitions: 1, Strategies: 113.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/queues.py", line 241, in _feed
    obj = ForkingPickler.dumps(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'axelrod.strategy_transformers.BackStabber'>: attribute lookup BackStabber on axelrod.strategy_transformers failed
```

Can someone confirm?

**Comment by drvinceknight** [comment]
I get the same error when running from `master`.

**Comment by drvinceknight** [comment]
`python3.5 run_axelrod --noise 0.05 -r 1 -o assets -p 0` gives same bug (as expected).

**Comment by drvinceknight** [comment]
Have raised https://github.com/Axelrod-Python/Axelrod/issues/516 on the library repo.

**Comment by drvinceknight** [comment]
Closing this as it's been looked at on the tournament repo.
